name: multi_date_picker
description: "This is pub package that lets user pick single or multiple dates and could be used of check-in check-out flow."
homepage: https://github.com/geek-vikas/multi-date-picker
version: 0.0.1-beta.1

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
